- name: Install packages for console
  package: name={{ item }}
           state=present
  with_items:
    - libapache2-mod-authnz-external
    - pwauth
  when: is_debuntu
  tags:
    - download

- name: Enable ssl
  apache2_module: name=ssl
  when: is_debuntu

- name: Create admin-console directory tree
  file: path={{ item }}
        mode=0755
        owner=root
        group=root
        state=directory
  with_items:
    - "{{ admin_console_dir }}"
    - "{{ admin_console_dir }}/css"
    - "{{ admin_console_dir }}/help"
    - "{{ admin_console_dir }}/js"
    - "{{ admin_console_dir }}/htmlf"
    - "{{ admin_console_dir }}/map"

- name: Copy admin-console css files
  copy: src={{ item }}
        dest="{{ admin_console_dir }}/css"
        mode=0644
        owner=root
        group=root
  with_fileglob:
        - css/*.css

- name: Copy admin-console help files
  copy: src={{ item }}
        dest="{{ admin_console_dir }}/help"
        mode=0644
        owner=root
        group=root
  with_fileglob:
        - help/*

- name: Copy admin-console javascript files
  copy: src={{ item }}
        dest="{{ admin_console_dir }}/js"
        mode=0644
        owner=root
        group=root
  with_fileglob:
        - js/*

- name: Copy admin-console html fragment files
  copy: src={{ item }}
        dest="{{ admin_console_dir }}/htmlf"
        mode=0644
        owner=root
        group=root
  with_fileglob:
        - htmlf/*

# after this branch is merged into master, enable the following
#- name: Fetch the javascript bundle with openlayers module
#  get_url:
#     url: "{{ iiab_map_url }}/admin-console/main.js"
#     dest: "{{ admin_console_dir }}/map/main.js"

# before the merge, use this version
- name: Temporary webpack bundle which interfaces with new map directory
  copy:
     src: map/main.js
     dest: "{{ admin_console_dir }}/map/main.js"

- name: Install admin-console config file
  template: src=admin-console.conf.j2
            dest=/etc/{{ apache_config_dir }}/admin-console.conf
            owner=root
            group=root
            mode=0644
  when: not adm_cons_force_ssl

- name: Delete admin-console config file
  file: path=/etc/{{ apache_config_dir }}/admin-console.conf
        state=absent
  when: adm_cons_force_ssl

- name: Install admin-console ssl config file
  template: src=admin-console-ssl.conf.j2
            dest=/etc/{{ apache_config_dir }}/admin-console-ssl.conf
            owner=root
            group=root
            mode=0644
  when: adm_cons_force_ssl

- name: Delete admin-console ssl config file
  file: path=/etc/{{ apache_config_dir }}/admin-console-ssl.conf
        state=absent
  when: not adm_cons_force_ssl

- name: Remove the debian default config which gets in the way
  file: path=/etc/apache2/sites-enabled/000-default.conf
        state=absent
  when: is_debuntu

# without ssl
- name: Make the admin-console enabled in apache2
  file: state=link
        dest=/etc/apache2/sites-enabled/admin-console.conf
        src=/etc/{{ apache_config_dir }}/admin-console.conf
  when: is_debuntu and not adm_cons_force_ssl

- name: Make the admin-console ssl version disabled in apache2
  file: path=/etc/apache2/sites-enabled/admin-console-ssl.conf
        state=absent
  when: is_debuntu and not adm_cons_force_ssl

# with ssl
- name: Add link for admin-console config file with ssl support
  file: path=/etc/apache2/sites-enabled/admin-console-ssl.conf
        src=/etc/{{ apache_config_dir }}/admin-console-ssl.conf
        state=link
  when: is_debuntu and adm_cons_force_ssl

- name: Remove link for admin-console config file with ssl support
  file: path=/etc/apache2/sites-enabled/admin-console.conf
        state=absent
  when: adm_cons_force_ssl and is_debuntu

- name: Install admin-console service
  template: src=cmd-service.wsgi.j2
            dest="{{ admin_console_dir }}/cmd-service.wsgi"
            owner=root
            group=root
            mode=0644

- name: Install admin-console service config file
  template: src=cmd-service.conf.j2
            dest=/etc/{{ apache_config_dir }}/cmd-service.conf
            owner=root
            group=root
            mode=0644

- name: Make the admin-console service enabled in apache2
  file: state=link
        dest=/etc/apache2/sites-enabled/cmd-service.conf
        src=/etc/{{ apache_config_dir }}/cmd-service.conf
  when: is_debuntu

- name: Install admin-console server info service
  template: src=server-info.php
            dest="{{ admin_console_dir }}/server-info.php"
            owner=root
            group=root
            mode=0644

- name: Install icon upload service
  template: src=upload-image.php
            dest="{{ admin_console_dir }}/upload-image.php"
            owner=root
            group=root
            mode=0644

- name: Install admin-console app
  copy: src=index.html
        dest="{{ admin_console_dir }}/index.html"
        owner=root
        group=root
        mode=0644

- name: Restart web server
  service: name={{ apache_service }}
           state=restarted
